[tool.poetry]
name = "site-search"
version = "0.1.0"
description = ""
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
requests = "^2.28.1"
ultimate-sitemap-parser = "^0.5"
beautifulsoup4 = "^4.11.1"
tqdm = "^4.64.0"
sentence-transformers = "^2.2.2"
fastapi = "^0.79.1"
qdrant-client = "0.9.2"
uvicorn = "^0.18.2"
scipy = "1.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
